//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session_4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rulons_Products
    {
        public int ID_Rulon_Product { get; set; }
        public string Product_ID { get; set; }
        public string Rulon_ID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Rulon Rulon { get; set; }
    }
}
